### ISSUE TITLE
Implement a `groupBy` parameter in `RepositoryReadConductor#FindAll`

### ISSUE THREAD

**Issue by mrjones2014** [AndcultureCode/AndcultureCode.CSharp.Conductors#19]
This issue depends on AndcultureCode/AndcultureCode.CSharp.Core#48, which would add the parameter to the interface. This issue is to implement the new parameter from the interface.

**Comment by dzoccarato** [comment]
Hi @mrjones2014 , I've did something for this: https://github.com/AndcultureCode/AndcultureCode.CSharp.Conductors/pull/24.
After closed of https://github.com/AndcultureCode/AndcultureCode.CSharp.Core/issues/48, I've update the package reference on projects on this PR.
Would you like to take a look?

**Comment by brandongregoryscott** [comment]
Closed with #24 ([v1.2.0](https://github.com/AndcultureCode/AndcultureCode.CSharp.Conductors/releases/tag/v1.2.0))
