### ISSUE TITLE
Implement `FindById` overload which accepts an additional filter

### ISSUE THREAD

**Issue by mrjones2014** [AndcultureCode/AndcultureCode.CSharp.Conductors#25]
Depends on AndcultureCode/AndcultureCode.CSharp.Core#61

Implement the overload described in the linked issue, a `FindById` that also accepts an additional filter.

CC: @ralphjmcintyre

**Comment by brandongregoryscott** [comment]
Forgot to circle back here, but published with [v1.3.0](https://github.com/AndcultureCode/AndcultureCode.CSharp.Conductors/releases/tag/v1.3.0)
